version: '3.8'

services:
  whisper-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fnwispr-server
    ports:
      - "8000:8000"
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount a cache directory for Whisper models
      - whisper-models:/root/.cache/whisper
    networks:
      - fnwispr-network

volumes:
  whisper-models:
    driver: local

networks:
  fnwispr-network:
    driver: bridge
